name: els-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - h5py
  - seaborn
  - scikit-learn
  - pingouin=0.5.5
  - ipykernel
  - jupyter
  - pip:
    - gspread
    - oauth2client
    - gspread-dataframe
    - python-dotenv
    
  

  